x-common-settings: &common-settings
  build:
    context: .
    dockerfile: ./containers/django.DEV.Dockerfile
  depends_on:
    postgres:
      condition: service_healthy
  env_file:
    - .env
  volumes:
    - ./apiserver:/app
    - static_DEV:/data/static
    - media_DEV:/data/media

services:
  django:
    <<: *common-settings
    container_name: letteranne_django_DEV
    command: /start-dev.sh
    init: true
    tty: true
    ports:
      - 8000:8000

  postgres:
    image: docker.io/postgres:16.2
    container_name: letteranne_postgres_DEV
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
        ]
      interval: 3s
      timeout: 3s
      retries: 30
    init: true
    volumes:
      - postgres_data_DEV:/var/lib/postgresql/data

volumes:
  postgres_data_DEV: {}
  media_DEV: {}
  static_DEV: {}
