x-common-settings: &common-settings
  build:
    context: .
    dockerfile: ./containers/django.DEV.Dockerfile
  depends_on:
    postgres:
      condition: service_healthy
  env_file:
    - .env
  volumes:
    - .:/app
    - static_DEV:/data/static
    - media_DEV:/data/media

services:
  django:
    <<: *common-settings
    container_name: letteranne_django_DEV
    command: /start-dev.sh
    init: true
    tty: true
    ports:
      - 8000:8000

  postgres:
    image: docker.io/postgres:16.2
    container_name: letteranne_postgres_DEV
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
        ]
      interval: 3s
      timeout: 3s
      retries: 30
    init: true
    volumes:
      - postgres_data_DEV:/var/lib/postgresql/data

  docs:
    container_name: letteranne_docs_DEV
    image: docker.io/squidfunk/mkdocs-material
    command: ["serve", "--dev-addr=0.0.0.0:4000"]
    ports:
      - 4000:4000
    volumes:
    - ./docs:/docs
    stdin_open: true
    tty: true

  mailcrab:
    image: docker.io/marlonb/mailcrab:latest
    ports:
      - 1080:1080
      - 1025:1025
    networks: [default]

volumes:
  postgres_data_DEV: {}
  media_DEV: {}
  static_DEV: {}
