/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Letteranne API
 * Headless API for delayed digital letter exchange, open letters, discovery, profiles, postcard collections, and basic moderation.

 * OpenAPI spec version: 1.0.0
 */
export interface RegisterRequest {
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthUserResponse {
  user: User;
}

export interface User {
  id: string;
  email: string;
  displayId: string;
  createdAt: string;
}

export interface PublicUser {
  id: string;
  displayId: string;
  profile?: Profile;
}

export interface Profile {
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
}

export interface ProfileUpdateRequest {
  /** @maxLength 500 */
  bio?: string;
  avatarUrl?: string;
}

export type LetterVisibility = (typeof LetterVisibility)[keyof typeof LetterVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LetterVisibility = {
  private: "private",
  open: "open"
} as const;

export type LetterStatus = (typeof LetterStatus)[keyof typeof LetterStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LetterStatus = {
  queued: "queued",
  delivered: "delivered",
  hidden_moderation: "hidden_moderation"
} as const;

export interface Letter {
  id: string;
  senderId: string;
  /** @nullable */
  recipientId?: string | null;
  /** @nullable */
  parentLetterId?: string | null;
  visibility: LetterVisibility;
  status: LetterStatus;
  /** @nullable */
  subject?: string | null;
  body: string;
  scheduledFor: string;
  /** @nullable */
  deliveredAt?: string | null;
  createdAt: string;
}

export interface LetterCreateRequest {
  visibility: LetterVisibility;
  /** @nullable */
  recipientId?: string | null;
  subject?: string;
  /** @minLength 1 */
  body: string;
  scheduledFor: string;
}

export interface LetterListResponse {
  items: Letter[];
  page: number;
  limit: number;
  total: number;
}

export interface UserPostcard {
  id: string;
  postcardId: string;
  title: string;
  imageUrl: string;
  unlockedAt: string;
}

export interface LetterPostcard {
  id: string;
  letterId: string;
  userPostcardId: string;
}

export type ModerationReportStatus =
  (typeof ModerationReportStatus)[keyof typeof ModerationReportStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModerationReportStatus = {
  open: "open",
  reviewed: "reviewed",
  dismissed: "dismissed",
  actioned: "actioned"
} as const;

export interface ModerationReport {
  id: string;
  letterId: string;
  reporterUserId: string;
  reason: string;
  status: ModerationReportStatus;
  createdAt: string;
}

export interface Error {
  code: string;
  message: string;
}

/**
 * Bad request
 */
export type BadRequestResponse = Error;

/**
 * Unauthorized
 */
export type UnauthorizedResponse = Error;

/**
 * Forbidden
 */
export type ForbiddenResponse = Error;

/**
 * Resource not found
 */
export type NotFoundResponse = Error;

/**
 * Resource conflict
 */
export type ConflictResponse = Error;

export type PageParameter = number;

export type LimitParameter = number;

export type DiscoverUsersParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParameter;
};

export type DiscoverUsers200 = {
  items: PublicUser[];
};

export type ListMyLettersParams = {
  /**
   * @minimum 1
   */
  page?: PageParameter;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParameter;
  visibility?: LetterVisibility;
};

export type ListOpenLettersParams = {
  /**
   * @minimum 1
   */
  page?: PageParameter;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParameter;
};

export type ReplyToOpenLetterBody = {
  /** @minLength 1 */
  body: string;
  subject?: string;
};

export type ListMyPostcards200 = {
  items: UserPostcard[];
};

export type AttachPostcardToLetterBody = {
  userPostcardId: string;
};

export type CreateModerationReportBody = {
  letterId: string;
  /** @minLength 5 */
  reason: string;
};

/**
 * @summary Register new user
 */
export type registerUserResponse201 = {
  data: AuthUserResponse;
  status: 201;
};

export type registerUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type registerUserResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type registerUserResponseSuccess = registerUserResponse201 & {
  headers: Headers;
};
export type registerUserResponseError = (registerUserResponse400 | registerUserResponse409) & {
  headers: Headers;
};

export type registerUserResponse = registerUserResponseSuccess | registerUserResponseError;

export const getRegisterUserUrl = () => {
  return `/auth/register`;
};

export const registerUser = async (
  registerRequest: RegisterRequest,
  options?: RequestInit
): Promise<registerUserResponse> => {
  const res = await fetch(getRegisterUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerRequest)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerUserResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as registerUserResponse;
};

/**
 * @summary Authenticate user session
 */
export type loginUserResponse200 = {
  data: AuthUserResponse;
  status: 200;
};

export type loginUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type loginUserResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type loginUserResponseSuccess = loginUserResponse200 & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse400 | loginUserResponse401) & {
  headers: Headers;
};

export type loginUserResponse = loginUserResponseSuccess | loginUserResponseError;

export const getLoginUserUrl = () => {
  return `/auth/login`;
};

export const loginUser = async (
  loginRequest: LoginRequest,
  options?: RequestInit
): Promise<loginUserResponse> => {
  const res = await fetch(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequest)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginUserResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as loginUserResponse;
};

/**
 * @summary End user session
 */
export type logoutUserResponse204 = {
  data: void;
  status: 204;
};

export type logoutUserResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type logoutUserResponseSuccess = logoutUserResponse204 & {
  headers: Headers;
};
export type logoutUserResponseError = logoutUserResponse401 & {
  headers: Headers;
};

export type logoutUserResponse = logoutUserResponseSuccess | logoutUserResponseError;

export const getLogoutUserUrl = () => {
  return `/auth/logout`;
};

export const logoutUser = async (options?: RequestInit): Promise<logoutUserResponse> => {
  const res = await fetch(getLogoutUserUrl(), {
    ...options,
    method: "POST"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: logoutUserResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as logoutUserResponse;
};

/**
 * @summary Get own profile
 */
export type getMyProfileResponse200 = {
  data: Profile;
  status: 200;
};

export type getMyProfileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getMyProfileResponseSuccess = getMyProfileResponse200 & {
  headers: Headers;
};
export type getMyProfileResponseError = getMyProfileResponse401 & {
  headers: Headers;
};

export type getMyProfileResponse = getMyProfileResponseSuccess | getMyProfileResponseError;

export const getGetMyProfileUrl = () => {
  return `/profiles/me`;
};

export const getMyProfile = async (options?: RequestInit): Promise<getMyProfileResponse> => {
  const res = await fetch(getGetMyProfileUrl(), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMyProfileResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getMyProfileResponse;
};

/**
 * @summary Update own profile
 */
export type updateMyProfileResponse200 = {
  data: Profile;
  status: 200;
};

export type updateMyProfileResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateMyProfileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateMyProfileResponseSuccess = updateMyProfileResponse200 & {
  headers: Headers;
};
export type updateMyProfileResponseError = (
  | updateMyProfileResponse400
  | updateMyProfileResponse401
) & {
  headers: Headers;
};

export type updateMyProfileResponse = updateMyProfileResponseSuccess | updateMyProfileResponseError;

export const getUpdateMyProfileUrl = () => {
  return `/profiles/me`;
};

export const updateMyProfile = async (
  profileUpdateRequest: ProfileUpdateRequest,
  options?: RequestInit
): Promise<updateMyProfileResponse> => {
  const res = await fetch(getUpdateMyProfileUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(profileUpdateRequest)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateMyProfileResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateMyProfileResponse;
};

/**
 * @summary Find user by public display ID
 */
export type getUserByDisplayIdResponse200 = {
  data: PublicUser;
  status: 200;
};

export type getUserByDisplayIdResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getUserByDisplayIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getUserByDisplayIdResponseSuccess = getUserByDisplayIdResponse200 & {
  headers: Headers;
};
export type getUserByDisplayIdResponseError = (
  | getUserByDisplayIdResponse401
  | getUserByDisplayIdResponse404
) & {
  headers: Headers;
};

export type getUserByDisplayIdResponse =
  | getUserByDisplayIdResponseSuccess
  | getUserByDisplayIdResponseError;

export const getGetUserByDisplayIdUrl = (displayId: string) => {
  return `/users/by-id/${displayId}`;
};

export const getUserByDisplayId = async (
  displayId: string,
  options?: RequestInit
): Promise<getUserByDisplayIdResponse> => {
  const res = await fetch(getGetUserByDisplayIdUrl(displayId), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserByDisplayIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUserByDisplayIdResponse;
};

/**
 * @summary Get randomized user discovery list
 */
export type discoverUsersResponse200 = {
  data: DiscoverUsers200;
  status: 200;
};

export type discoverUsersResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type discoverUsersResponseSuccess = discoverUsersResponse200 & {
  headers: Headers;
};
export type discoverUsersResponseError = discoverUsersResponse401 & {
  headers: Headers;
};

export type discoverUsersResponse = discoverUsersResponseSuccess | discoverUsersResponseError;

export const getDiscoverUsersUrl = (params?: DiscoverUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/discover?${stringifiedParams}` : `/users/discover`;
};

export const discoverUsers = async (
  params?: DiscoverUsersParams,
  options?: RequestInit
): Promise<discoverUsersResponse> => {
  const res = await fetch(getDiscoverUsersUrl(params), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: discoverUsersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as discoverUsersResponse;
};

/**
 * @summary List current user's letter history
 */
export type listMyLettersResponse200 = {
  data: LetterListResponse;
  status: 200;
};

export type listMyLettersResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type listMyLettersResponseSuccess = listMyLettersResponse200 & {
  headers: Headers;
};
export type listMyLettersResponseError = listMyLettersResponse401 & {
  headers: Headers;
};

export type listMyLettersResponse = listMyLettersResponseSuccess | listMyLettersResponseError;

export const getListMyLettersUrl = (params?: ListMyLettersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/letters?${stringifiedParams}` : `/letters`;
};

export const listMyLetters = async (
  params?: ListMyLettersParams,
  options?: RequestInit
): Promise<listMyLettersResponse> => {
  const res = await fetch(getListMyLettersUrl(params), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMyLettersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listMyLettersResponse;
};

/**
 * @summary Create a private or open letter
 */
export type createLetterResponse201 = {
  data: Letter;
  status: 201;
};

export type createLetterResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type createLetterResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createLetterResponseSuccess = createLetterResponse201 & {
  headers: Headers;
};
export type createLetterResponseError = (createLetterResponse400 | createLetterResponse401) & {
  headers: Headers;
};

export type createLetterResponse = createLetterResponseSuccess | createLetterResponseError;

export const getCreateLetterUrl = () => {
  return `/letters`;
};

export const createLetter = async (
  letterCreateRequest: LetterCreateRequest,
  options?: RequestInit
): Promise<createLetterResponse> => {
  const res = await fetch(getCreateLetterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(letterCreateRequest)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLetterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createLetterResponse;
};

/**
 * @summary Get letter details
 */
export type getLetterResponse200 = {
  data: Letter;
  status: 200;
};

export type getLetterResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getLetterResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getLetterResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getLetterResponseSuccess = getLetterResponse200 & {
  headers: Headers;
};
export type getLetterResponseError = (
  | getLetterResponse401
  | getLetterResponse403
  | getLetterResponse404
) & {
  headers: Headers;
};

export type getLetterResponse = getLetterResponseSuccess | getLetterResponseError;

export const getGetLetterUrl = (letterId: string) => {
  return `/letters/${letterId}`;
};

export const getLetter = async (
  letterId: string,
  options?: RequestInit
): Promise<getLetterResponse> => {
  const res = await fetch(getGetLetterUrl(letterId), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLetterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getLetterResponse;
};

/**
 * @summary List public open letters
 */
export type listOpenLettersResponse200 = {
  data: LetterListResponse;
  status: 200;
};

export type listOpenLettersResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type listOpenLettersResponseSuccess = listOpenLettersResponse200 & {
  headers: Headers;
};
export type listOpenLettersResponseError = listOpenLettersResponse401 & {
  headers: Headers;
};

export type listOpenLettersResponse = listOpenLettersResponseSuccess | listOpenLettersResponseError;

export const getListOpenLettersUrl = (params?: ListOpenLettersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/letters/open?${stringifiedParams}` : `/letters/open`;
};

export const listOpenLetters = async (
  params?: ListOpenLettersParams,
  options?: RequestInit
): Promise<listOpenLettersResponse> => {
  const res = await fetch(getListOpenLettersUrl(params), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listOpenLettersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listOpenLettersResponse;
};

/**
 * @summary Reply to an open letter
 */
export type replyToOpenLetterResponse201 = {
  data: Letter;
  status: 201;
};

export type replyToOpenLetterResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type replyToOpenLetterResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type replyToOpenLetterResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type replyToOpenLetterResponseSuccess = replyToOpenLetterResponse201 & {
  headers: Headers;
};
export type replyToOpenLetterResponseError = (
  | replyToOpenLetterResponse400
  | replyToOpenLetterResponse401
  | replyToOpenLetterResponse404
) & {
  headers: Headers;
};

export type replyToOpenLetterResponse =
  | replyToOpenLetterResponseSuccess
  | replyToOpenLetterResponseError;

export const getReplyToOpenLetterUrl = (letterId: string) => {
  return `/letters/${letterId}/replies`;
};

export const replyToOpenLetter = async (
  letterId: string,
  replyToOpenLetterBody: ReplyToOpenLetterBody,
  options?: RequestInit
): Promise<replyToOpenLetterResponse> => {
  const res = await fetch(getReplyToOpenLetterUrl(letterId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(replyToOpenLetterBody)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: replyToOpenLetterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as replyToOpenLetterResponse;
};

/**
 * @summary Get current user's postcard collection
 */
export type listMyPostcardsResponse200 = {
  data: ListMyPostcards200;
  status: 200;
};

export type listMyPostcardsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type listMyPostcardsResponseSuccess = listMyPostcardsResponse200 & {
  headers: Headers;
};
export type listMyPostcardsResponseError = listMyPostcardsResponse401 & {
  headers: Headers;
};

export type listMyPostcardsResponse = listMyPostcardsResponseSuccess | listMyPostcardsResponseError;

export const getListMyPostcardsUrl = () => {
  return `/postcards/collection`;
};

export const listMyPostcards = async (options?: RequestInit): Promise<listMyPostcardsResponse> => {
  const res = await fetch(getListMyPostcardsUrl(), {
    ...options,
    method: "GET"
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMyPostcardsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listMyPostcardsResponse;
};

/**
 * @summary Attach owned postcard to a letter
 */
export type attachPostcardToLetterResponse201 = {
  data: LetterPostcard;
  status: 201;
};

export type attachPostcardToLetterResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type attachPostcardToLetterResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type attachPostcardToLetterResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type attachPostcardToLetterResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type attachPostcardToLetterResponseSuccess = attachPostcardToLetterResponse201 & {
  headers: Headers;
};
export type attachPostcardToLetterResponseError = (
  | attachPostcardToLetterResponse400
  | attachPostcardToLetterResponse401
  | attachPostcardToLetterResponse403
  | attachPostcardToLetterResponse404
) & {
  headers: Headers;
};

export type attachPostcardToLetterResponse =
  | attachPostcardToLetterResponseSuccess
  | attachPostcardToLetterResponseError;

export const getAttachPostcardToLetterUrl = (letterId: string) => {
  return `/letters/${letterId}/postcard`;
};

export const attachPostcardToLetter = async (
  letterId: string,
  attachPostcardToLetterBody: AttachPostcardToLetterBody,
  options?: RequestInit
): Promise<attachPostcardToLetterResponse> => {
  const res = await fetch(getAttachPostcardToLetterUrl(letterId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(attachPostcardToLetterBody)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: attachPostcardToLetterResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as attachPostcardToLetterResponse;
};

/**
 * @summary Report abusive open-letter content
 */
export type createModerationReportResponse201 = {
  data: ModerationReport;
  status: 201;
};

export type createModerationReportResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type createModerationReportResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createModerationReportResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type createModerationReportResponseSuccess = createModerationReportResponse201 & {
  headers: Headers;
};
export type createModerationReportResponseError = (
  | createModerationReportResponse400
  | createModerationReportResponse401
  | createModerationReportResponse404
) & {
  headers: Headers;
};

export type createModerationReportResponse =
  | createModerationReportResponseSuccess
  | createModerationReportResponseError;

export const getCreateModerationReportUrl = () => {
  return `/moderation/reports`;
};

export const createModerationReport = async (
  createModerationReportBody: CreateModerationReportBody,
  options?: RequestInit
): Promise<createModerationReportResponse> => {
  const res = await fetch(getCreateModerationReportUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createModerationReportBody)
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createModerationReportResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createModerationReportResponse;
};
